repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.4" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        types_or: [ css, javascript, ts, tsx, markdown ]

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: [ --safe,  server]
