version: "3.9"

services:
  mongodb:
    image: mongo:4.4.6
    container_name: examanager-db

  examanager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: examanager-app
    environment:
      MONGO_HOST: "mongodb"
      INIT_ADMIN_USER: true
    ports:
      - "5200:5200"
    depends_on:
      - mongodb