version: "3.9"

services:
  mongodb:
    image: mongo
    container_name: examanager-db
    ports:
      - "27017:27017"

  examanager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: examanager-app
    environment:
      MONGO_HOST: "mongodb"
    ports:
      - "5200:5200"
    depends_on:
      - mongodb