[tool.poetry]
name = "server"
version = "0.1.0"
description = ""
authors = ["Benedikt Lüken-Winkels <belu02@dfki.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
